applicationTitle: DunceHouse DirecTV # What the DirecTV UI might have looked like in 2012

noise: 0 
blur: false 
bezel: flat 
changeChannelNoise: false

refs:
  placeholder: 
    image: directv.png
  webn:
  backgroundAudio: https://stream.revma.ihrhls.com/zc1701/hls.m3u8?streamid=1701&zip=&aw_0_1st.playerid=iHeartRadioWebPlayer&aw_0_1st.skey=11554381129&clientType=web&companionAds=false&deviceName=web-mobile&dist=iheart&host=webapp.US&listenerId=&playedFrom=157&pname=live_profile&profileId=11554381129&stationid=1701&terminalId=159&territory=US
  placeholder2: 
    image: place2.png
  closed: 
    image: deadchannel.png
    description:  This channel is no longer available.
  error: 
    image: tverror.png
    description: Channel not available. Please try another channel.

osd:
  theme: sat2012
  aspectRatioBehavior: stretch 
  themeOptions:
    providerLogo: files/directv_large.png 
    extraMenuItemsBefore:
      - Messages
    extraMenuItemsAfter:
      - CC
      - Last 4
      - Favorites
      - Audio/Video
      - Parental

noSignalContent:
  image: files/DirecTV_Slide.png
  backgroundAudio: https://file.garden/aUYIWVAKvQxCBY-_/soho-sound.mp3

defaultChannel: 1

dimensions:
  screenWidth: 640 
  screenHeight: 360


channels:

- number: 1
  name: Old Timey Computer Show
  abbr: OTCS
  video: 
   src: https://otcs.minuspoint.com/hls/0/stream.m3u8?cachebust=3146f9
   volume: false
  backgroundAudio: https://file.garden/aUYIWVAKvQxCBY-_/soho-sound.mp3
   

- number: 2
  name: Program Guide
  title: Electronic Program Guide
  noise: 0.1
  guide:
        logo: https://upload.wikimedia.org/wikipedia/commons/4/46/Windows_7_Classic_Error_Active.png
        alerts:
          - position: 10
            image: https://upload.wikimedia.org/wikipedia/commons/4/46/Windows_7_Classic_Error_Active.png
          - position: 30
            image: https://upload.wikimedia.org/wikipedia/commons/1/1c/Android_4.1_lockscreen_on_Galaxy_Nexus_20120712.jpg
          - position: 50
            image: https://upload.wikimedia.org/wikipedia/commons/1/1c/Android_4.1_lockscreen_on_Galaxy_Nexus_20120712.jpg


    
- number: 3
  name: Oak Ridge TV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8


- number: 4
  name: Albuquerque
  video: https://cmd-hue.github.io/albuquerque.mp4

- number: 5
  name: Greenhill Public Access
  video: 
   src: https://ch2.tvs.gcpw.art/stream_480p.m3u8
   volume: false
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3


- number: 6
  name: Placeholder Channel
  ref: placeholder

- number: 7
  name: Southwest Florida weather and live streaming webcams
  ref: error

- number: 8
  name: Blue Screen 
  color: blue

- number: 9
  name: DirecTV ScreenSaver
  bouncing-logo: dtvlogo.webp

- number: 10
  name: Info Channel
  image: info.png

- number: 11
  abbr: CTV
  name: CMDTV
  icon: https://cmd-hue.github.io/logo.png
  iframe: 
   src: https://cmd-hue.github.io/cmdtv

- number: 12
  name: AL! Lottery - Weird Al Keno
  abbr: KENO
  icon: https://cmd-hue.github.io/guide2/logoalt.png
  keno:
   drawingMinutes: 2
   drawIntervalMs: 800
   centerText: Weird Al Keno

- number: 13
  name: Audio Visualizer Test
  visualizer: https://cmd-hue.github.io/assets/joyfulblud.mp3

- number: 14
  name: Picsum Test
  image: https://fastly.picsum.photos/640/480

- number: 15
  name: Toon Goggles
  video: https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=37

- number: 16
  name: Toon Goggles Alternate
  video: https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=35

- number: 17
  name: Film4
  ref: closed

- number: 18
  name: News
  feed-reader:
    src: https://moxie.foxnews.com/google-publisher/us.xml
    title: News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6


- number: 19
  name: Fox Weather 24/7
  video: https://247wlive.foxweather.com/stream/index_640x360.m3u8


- number: 20
  name: CBBC/BBC THREE
  video: https://viamotionhsi.netplus.ch/live/eds/bbc3cbbc/browser-HLS8/bbc3cbbc.m3u8

- number: 21
  name: Disney XD
  video: https://fl7.moveonjoy.com/DISNEY_XD/index.m3u8
  icon: https://upload.wikimedia.org/wikipedia/commons/a/a8/2015_Disney_XD_logo.svg

- number: 22
  name: Cartoon Network
  video: https://fl61.moveonjoy.com/CARTOON_NETWORK/playlist.m3u8
  description: Nightshares With Adult Swim 5:00PM - 6:00AM Eastern Time
  icon: https://upload.wikimedia.org/wikipedia/commons/8/80/Cartoon_Network_2010_logo.svg

- number: 23
  name: Nickelodeon
  video: https://fl31.moveonjoy.com/NICKELODEON/index.m3u8
  description: Nightshares With nick at nite 5:00PM - 6:00AM Eastern Time
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5f/Nickelodeon_logo_%282003%2C_short_name%29.svg

- number: 24
  name: VH1 Soul
  video: https://fl1.moveonjoy.com/BET_SOUL/index.m3u8
  icon: https://upload.wikimedia.org/wikipedia/en/8/8d/VH1_Soul.svg


- number: 25
  name: FGTEEV
  video: https://amg00285-amg00285c3-firetv-us-6596.playouts.now.amagi.tv/playlist240p.m3u8
  icon: https://yt3.ggpht.com/8lYzEQAP23681vKEG0ahOTlsM6kBwvq8fNDWgNzhq8cYTlPcBVWGZifL6huG9M_3AedplOvpjlQ=s176-c-k-c0x00ffffff-no-rj-mo

- number: 26
  name: NickToons
  description: Nicktoons is the brand name used by Nickelodeon for their original animated series.
  video: https://fl1.moveonjoy.com/NICKTOONS/index.m3u8

- number: 27
  name: California Music
  video: https://cmc-ono.amagi.tv/hls/amagi_hls_data_cmcAAAAAA-cmc-ono/CDN/640x360_1205600/index.m3u8

- number: 28
  name: Disney Channel
  video: https://fl31.moveonjoy.com/DISNEY/index.m3u8

- number: 29
  name: BBC Three
  video: https://streamer.nexyl.uk/39290a19-b8dd-43ea-b8dc-081c37790f24.m3u8

- number: 30
  name: Cartoon Rewind
  video: https://amg00136-wbd-amg00136c75-tablo-us-7211.playouts.now.amagi.tv/playlist240P.m3u8

- number: 31
  name: Music Choice Rock
  video: https://edge.music-choice-chaina.top.comcast.net/streamwebaca3/AudioChannels/44/O0U9MTc3MDA3Njc0ODtBPTE7Sz0wO1A9MDExMTA7Uz0wZTRhMmJiNmVlOGQwZGRiYmRjMDNmMjFlZjNjYzY2MGZjMjE0ZmU5/chunklist.m3u8

- number: 32
  name: Maryland Public Television
  abbr: WWPB
  icon: placeholders/pbs.png
  title: Maryland Public Television
  video:
   volume: true
   provider: hls
   src: https://2-fss-2.streamhoster.com/pl_138/amlst:201814-1291584/chunklist_b4000000.m3u8

