noise: 0.15
shadowMask: aperture-grille
bezel: flat
refs:
  placeholder: 
    image: directv.png


defaultChannel: 0

channels:
- number: 0
  name: Weird Al Lottery
  keno:
  drawingMinutes: 5
  drawIntervalMs: 400
  centerText: Weird Al Lottery - WAL

- number: 1
  name: Program Guide
  title: Electronic Program Guide
  noise: 0.1
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3
  guide:
    theme: 1989
    themeOptions:
      title: Greenhill Cable TV Guide
      ticker: 
      - "Greenhill cable - connecting you to the future"
      - "Happy Viewing from Greenhill Cable!"
      - "Try out Watermelons! Now available at a grocery store near you!"
      - "Greenhill cable - you ever seen a buttersock?"

    
- number: 2
  name: Oak Ridge TV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8


- number: 3
  name: Albuquerque
  video: https://cmd-hue.github.io/albuquerque.mp4

- number: 4
  name: Greenhill Public Access
  video: https://ch2.tvs.gcpw.art/stream_480p.m3u8
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3


- number: 5
  name: Placeholder Channel
  ref: placeholder
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3
  noise: 0.2

- number: 6
  name: Southwest Florida weather and live streaming webcams
  twitch: capeweather

- number: 7
  name: osd
  osd:
  tuner: true
  info: true
  receiver: true

- number: 8
  name: DirecTV ScreenSaver
  bouncing-logo: dtvlogo.webp

- number: 9
  name: CMDTV
  iframe:
  src: https://cmd-hue.github.io/cmdtv/

