noise: 0.15
shadowMask: aperture-grille
bezel: flat

defaultChannel: 1

channels:

- number: 16
  name: Program Guide
  abbr: EPG
  title: Electronic Program Guide
  noise: 0.1
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    description: Nightwave Plaza Radio 
    nowPlayingUrl: https://api.plaza.one/status 
    nowPlayingProvider: plaza-one 
osd:
  theme: sat2012

- number: 2
  abbr: RED
  name: Red Screen
  color: red



- number: 3 
  abbr: VIZ
  name: Visualizer
  visualizer:
  src: https://radio.plaza.one/mp3
  visualization: 1
  visualizationDuration: 0
    
- number: 4
  name: News
  abbr: NEWS
  feed-reader:
    src: https://docs.tvs.gcpw.art/tvs-changelog.xml
    title: News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 5
  name: Oak Ridge TV
  abbr: ORTV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8
  

- number: 6
  name: Falling in Lottery - Keno
  keno:
  drawingMinutes: 3
  drawIntervalMs: 1000

