noise: 0.15
shadowMask: aperture-grille
bezel: flat

defaultChannel: 1

channels:

- number: 1
  name: Program Guide
  abbr: EPG
  title: CMD HUE Program Guide
  noise: 0.1
  backgroundAudio: https://cmd-hue.github.io/assets/joyfulblud.mp3
  guide:
    theme: 1989
    themeOptions:
      title: CMD Cable TV Guide
      ticker: 
      - "Hypercom cable - connecting you to the future"


- number: 2
  abbr: Goob18
  name: Goob18 YouTube TV
  backgroundAudio: http://cmd-hue.github.io/assets/joyfulblud.mp3
  iframe: 
    src: https://goob18.github.io/ 

- number: 3
  name: Nickelodeon
  abbr: NKHD
  video: http://23.237.104.106:8080/USA_NICKELODEON/index.m3u8

- number: 4
  name: TBS
  abbr: TBSHD
  video: http://fl51.moveonjoy.com/TBS/index.m3u8
