noise: 0.3
shadowMask: aperture-grille
bezel: flat
refs:
  placeholder: 
    image: directv.png
  webn:
  backgroundAudio: https://stream.revma.ihrhls.com/zc1701/hls.m3u8?streamid=1701&zip=&aw_0_1st.playerid=iHeartRadioWebPlayer&aw_0_1st.skey=11554381129&clientType=web&companionAds=false&deviceName=web-mobile&dist=iheart&host=webapp.US&listenerId=&playedFrom=157&pname=live_profile&profileId=11554381129&stationid=1701&terminalId=159&territory=US
  placeholder2: 
    image: place2.png
  closed: 
    image: deadchannel.png
  error: 
    image: tverror.png

osd:
  theme: sat2012
  themeOptions:
    providerLogo: https://upload.wikimedia.org/wikipedia/commons/c/cf/Direct_tv_channel.svg

noSignalContent:
  image: nosignal.png

defaultChannel: 1



channels:

- number: 1
  name: texas wexas mexas
  ref: error
   

- number: 2
  name: Program Guide
  title: Electronic Program Guide
  noise: 0.1
  guide:
        logo: https://upload.wikimedia.org/wikipedia/commons/4/46/Windows_7_Classic_Error_Active.png
        alerts:
          - position: 10
            image: https://upload.wikimedia.org/wikipedia/commons/4/46/Windows_7_Classic_Error_Active.png
          - position: 30
            image: https://upload.wikimedia.org/wikipedia/commons/1/1c/Android_4.1_lockscreen_on_Galaxy_Nexus_20120712.jpg
          - position: 50
            image: https://upload.wikimedia.org/wikipedia/commons/1/1c/Android_4.1_lockscreen_on_Galaxy_Nexus_20120712.jpg


    
- number: 3
  name: Oak Ridge TV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8


- number: 4
  name: Albuquerque
  video: https://cmd-hue.github.io/albuquerque.mp4

- number: 5
  name: Greenhill Public Access
  video: 
   src: https://ch2.tvs.gcpw.art/stream_480p.m3u8
   volume: false
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3


- number: 6
  name: Placeholder Channel
  ref: placeholder

- number: 7
  name: Southwest Florida weather and live streaming webcams
  ref: error

- number: 8
  name: Blue Screen 
  color: blue

- number: 9
  name: DirecTV ScreenSaver
  bouncing-logo: dtvlogo.webp

- number: 10
  name: Info Channel
  image: info.png

- number: 11
  abbr: CTV
  name: CMDTV
  icon: https://cmd-hue.github.io/logo.png
  iframe: 
   src: https://cmd-hue.github.io/cmdtv

- number: 12
  name: AL! Lottery - Weird Al Keno
  abbr: KENO
  icon: https://cmd-hue.github.io/guide2/logoalt.png
  keno:
   drawingMinutes: 2
   drawIntervalMs: 800
   centerText: Weird Al Keno

- number: 13
  name: Audio Visualizer Test
  visualizer: https://cmd-hue.github.io/assets/joyfulblud.mp3

- number: 14
  name: Picsum Test
  image: https://fastly.picsum.photos/640/480

- number: 15
  name: Toon Goggles
  video: https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=37

- number: 16
  name: Toon Goggles Alternate
  video: https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=35

- number: 17
  name: Film4
  video: https://cache1a.netplus.ch/tok_eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNzcwMDQ1NDA2Iiwic2lwIjoiIiwicGF0aCI6Ii9saXZlL2Vkcy9maWxtNC9icm93c2VyLUhMUzgvIiwic2Vzc2lvbl9jZG5faWQiOiIzMDY3ZmQ3NjczMDM3Y2Y1Iiwic2Vzc2lvbl9pZCI6IiIsImNsaWVudF9pZCI6IiIsImRldmljZV9pZCI6IiIsIm1heF9zZXNzaW9ucyI6MCwic2Vzc2lvbl9kdXJhdGlvbiI6MCwidXJsIjoiaHR0cHM6Ly8xMC4wLjIyOS4xOSIsInNlc3Npb25fdGltZW91dCI6MCwiYXVkIjoiNTMiLCJzb3VyY2VzIjpbNDhdfQ==.Rqt_FNO-ecdsbnnVH-M_svUOQsYxyxTwMiZD3leg75LLuR4WXAzQPHaL0n46awJDj-93WBVGctMvSgkcFXP3kg==/live/eds/film4/browser-HLS8/film4.m3u8

- number: 18
  name: News
  feed-reader:
    src: https://moxie.foxnews.com/google-publisher/us.xml
    title: News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6


- number: 19
  name: Fox Weather 24/7
  video: https://247wlive.foxweather.com/stream/index_640x360.m3u8


- number: 20
  name: CBBC/BBC THREE
  video: https://viamotionhsi.netplus.ch/live/eds/bbc3cbbc/browser-HLS8/bbc3cbbc.m3u8

- number: 21
  name: Disney XD
  video: https://fl7.moveonjoy.com/DISNEY_XD/index.m3u8
  icon: https://upload.wikimedia.org/wikipedia/commons/a/a8/2015_Disney_XD_logo.svg

- number: 22
  name: Cartoon Network
  video: https://fl61.moveonjoy.com/CARTOON_NETWORK/playlist.m3u8
  description: Nightshares With Adult Swim 5:00PM - 6:00AM Eastern Time
  icon: https://upload.wikimedia.org/wikipedia/commons/8/80/Cartoon_Network_2010_logo.svg

- number: 23
  name: Nickelodeon
  video: https://fl31.moveonjoy.com/NICKELODEON/index.m3u8
  description: Nightshares With nick at nite 5:00PM - 6:00AM Eastern Time
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5f/Nickelodeon_logo_%282003%2C_short_name%29.svg

- number: 24
  name: VH1 Soul
  video: https://fl1.moveonjoy.com/BET_SOUL/index.m3u8
  icon: https://upload.wikimedia.org/wikipedia/en/8/8d/VH1_Soul.svg


