noise: 0.15
shadowMask: aperture-grille
bezel: flat

defaultChannel: 1

channels:

- number: 16
  name: Program Guide
  abbr: EPG
  title: Electronic Program Guide
  noise: 0.1
  guide:
    theme: 1989
    themeOptions:
      title: Greenhill Cable TV Guide
      ticker: 
      - "Greenhill cable - connecting you to the future"
      - "Happy Viewing from Greenhill Cable!"
      - "Try out Watermelons! Now available at a grocery store near you!"
      - "Greenhill cable - you ever seen a buttersock?"

- number: 2
  abbr: RED
  name: Red Screen
  color: red


- number: 3 
  abbr: VIZ
  name: Visualizer
  visualizer:
  src: https://radio.plaza.one/mp3
  visualization: 1
  visualizationDuration: 0
    
- number: 4
  name: News
  abbr: NEWS
  feed-reader:
    src: https://docs.tvs.gcpw.art/tvs-changelog.xml
    title: News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 5
  name: Oak Ridge TV
  abbr: ORTV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8
  

- number: 6
  name: Falling in Lottery - Keno
  noSignalContent: 
  image: directv.png
  keno:
  drawingMinutes: 3
  drawIntervalMs: 1000

