noise: 0.15
shadowMask: aperture-grille
bezel: flat
refs:
  placeholder: 
    image: directv.png
  webn:
  backgroundAudio: https://stream.revma.ihrhls.com/zc1701/hls.m3u8?streamid=1701&zip=&aw_0_1st.playerid=iHeartRadioWebPlayer&aw_0_1st.skey=11554381129&clientType=web&companionAds=false&deviceName=web-mobile&dist=iheart&host=webapp.US&listenerId=&playedFrom=157&pname=live_profile&profileId=11554381129&stationid=1701&terminalId=159&territory=US
  placeholder2: 
    image: place2.png
  closed: 
    image: deadchannel.png
  error: 
    image: tverror.png
defaultChannel: 1

channels:

- number: 1
  name: texas wexas mexas
  pip:
    a:
      ref: placeholder
    b:
      video: https://ch3.tvs.gcpw.art/stream_480p.m3u8

- number: 2
  name: Program Guide
  title: Electronic Program Guide
  noise: 0.1
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3
  guide:
    theme: 1989
    themeOptions:
      title: Greenhill Cable TV Guide
      ticker: 
      - "Greenhill cable - connecting you to the future"
      - "Happy Viewing from Greenhill Cable!"
      - "Try out Watermelons! Now available at a grocery store near you!"
      - "Greenhill cable - you ever seen a buttersock?"

    
- number: 3
  name: Oak Ridge TV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8


- number: 4
  name: Albuquerque
  video: https://cmd-hue.github.io/albuquerque.mp4

- number: 5
  name: Greenhill Public Access
  video: https://ch2.tvs.gcpw.art/stream_480p.m3u8
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3


- number: 6
  name: Placeholder Channel
  ref: placeholder
  noise: 0.5

- number: 7
  name: Southwest Florida weather and live streaming webcams
  ref: error

- number: 8
  name: osd
  osd:
  tuner: true
  info: true
  receiver: true

- number: 9
  name: DirecTV ScreenSaver
  bouncing-logo: dtvlogo.webp

- number: 10
  name: Info Channel
  image: info.png
  ref: webn

- number: 11
  abbr: CTV
  name: CMDTV
  iframe: 
   src: https://cmd-hue.github.io/cmdtv