noise: 0.15
shadowMask: aperture-grille
bezel: flat
refs:
  placeholder: 
    image: directv.png


defaultChannel: 1

channels:

- number: 1
  name: Program Guide
  abbr: EPG
  title: Electronic Program Guide
  noise: 0.1
  guide:
    theme: 1989
    themeOptions:
      title: Greenhill Cable TV Guide
      ticker: 
      - "Greenhill cable - connecting you to the future"
      - "Happy Viewing from Greenhill Cable!"
      - "Try out Watermelons! Now available at a grocery store near you!"
      - "Greenhill cable - you ever seen a buttersock?"

- number: 2
  abbr: RED
  name: Red Screen
  color: red

    
- number: 3
  name: Oak Ridge TV
  abbr: ORTV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8

- number: 4
  name: Falling in Lottery - Keno
  keno:
  drawingMinutes: 6
  drawIntervalMs: 2000
  centerText: Falling in Lottery

- number: 5
  name: Screaming Slides
  slideshow:
  duration: 10
  images:
  - https://picsum.photos/id/640/480
  - https://picsum.photos/id/640/480
  - https://picsum.photos/id/640/480