noise: 0.15
shadowMask: aperture-grille
bezel: flat

defaultChannel: 1

channels:

- number: 1 # As mentioned previously you can declare channels in any order; they'll be arranged when you begin.
  name: Program Guide
  abbr: GUIDE
  title: Prevue Guide
  noise: 0.1
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    description: Nightwave Plaza Radio # Optional. Credits will appear in the Info OSD
    nowPlayingUrl: https://api.plaza.one/status # Optional. If the radio service you're using has a song history API you can link to it here.
    nowPlayingProvider: plaza-one # Required if using nowPlayingUrl. Only a few providers are supported right now; see the documentation for more info.
  v-split: # Program guides are traditionally split in half; the top half is advertising and the lower half is the guide data. We use the v-split layout which defines two components, A and B.
    a: # A is the top part. See: https://greenhillplaza.notion.site/Layouts-728ab1198d4049de8f4b9a4ff6b31efe?pvs=4
      loop:
      - slideshow: # Image slideshow; at the end of it we'll advance to the next component in the loop.
          duration: 10 # Number of seconds per slide
          images:
            - ./placeholders/tips-02.png
            - ./placeholders/guide-ad-2.png
            - ./placeholders/tips-01.png
      - basic-text: # The basic-text engine can display a text slideshow from a data source with rich formatting.
          src: /config-examples/basic-text/guide-ads.json # This functionality will be improved in future versions; see https://greenhillplaza.notion.site/Basic-Text-9fdb10f4dc7841d28fe92e09904d9aea?pvs=4
          autoAdvance: true
      - slideshow:
          duration: 10
          images:
            
            - ./placeholders/guide-ad-3.png
            - ./placeholders/guide-ad-2.png
            - ./placeholders/guide-ad.png
    b: # B is the bottom part
      guide: # Program guides read the current channel lineup to reconstruct listings based off channel numbers, title and description. https://greenhillplaza.notion.site/Program-Guides-46e80919a3754efa9769f74dd00946fe?pvs=4
        logo: ./placeholders/guide-header.png # Logo to show at the top of the guide
        alerts: # "Alerts" that show up at certain positions in the guide.
          - position: 12 # The channel to show the alert after. Doesn't need to be a real channel.
            text: |
              Severe Thunderstorm Warning issued for Greenhill County until 6:00 PM
          - position: 100
            text: | # You can define text over multiple lines but it'll be compressed to a single line.
              The following county services are unavailable:
              Greenhill County Sheriff's Office
              Greenhill County Fire Department
              Greenhill County Emergency Services

- number: 2
  abbr: Goob18
  name: Goob18 YouTube TV
  backgroundAudio: http://cmd-hue.github.io/assets/joyfulblud.mp3
  iframe: 
    src: https://goob18.github.io/ 



- number: 3 
  abbr: Retro
  name: Retro TV
  visualizer:
  src: https://radio.plaza.one/mp3
  visualization: 1
  visualizationDuration: 0
    
- number: 4
  name: News
  abbr: NEWS
  feed-reader:
    src: https://docs.tvs.gcpw.art/tvs-changelog.xml
    title: News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 5
  name: Oak Ridge TV
  abbr: ORTV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8

- number: 6
  name: Gonzo Movies
  abbr: GNZMVS
  image: directv.png
  

- number: 7
  name: CMD HUE Radio
  abbr: CMDRAD
  image: directv.png
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    description: Nightwave Plaza Radio
    nowPlayingUrl: https://api.plaza.one/status
    nowPlayingProvider: plaza-one

- number: 8
  name: Falling in Lottery - Keno
  abbr: KENO
  backgroundAudio: https://n0ab-e2.revma.ihrhls.com/zc1701/hls.m3u8?rj-ttl=5&rj-tok=AAABnBqpKrMAAIXmuXV3e0Y63g&streamid=1701&zip=&aw_0_1st.playerid=iHeartRadioWebPlayer&aw_0_1st.skey=11554381129&clientType=web&companionAds=false&deviceName=web-mobile&dist=iheart&host=webapp.US&listenerId=&playedFrom=157&pname=live_profile&profileId=11554381129&stationid=1701&terminalId=159&territory=US
  keno:
  drawingMinutes: 2
  drawIntervalMs: 1000
  centerText: Falling in Lottery Keno Service

- number: 9
  name: Greenhill Public Access
  abbr: PUBACC
  video: https://ch2.tvs.gcpw.art/stream_480p.m3u8

- number: 10
  name: WX WeatherStar CMD HUE
  abbr: WX
  weather: 
    logo: https://cmd-hue.github.io/logo.png # Required. Channel logo in the corner
    provider: usa # Required. This is based on data from the US National Weather Service, and as such only works in the US.
    units: metric # Required. The units to use; either imperial or metric