noise: 0.15
shadowMask: aperture-grille
bezel: flat
refs:
  placeholder: 
    image: directv.png
  webn:
  backgroundAudio: https://stream.revma.ihrhls.com/zc1701/hls.m3u8?streamid=1701&zip=&aw_0_1st.playerid=iHeartRadioWebPlayer&aw_0_1st.skey=11554381129&clientType=web&companionAds=false&deviceName=web-mobile&dist=iheart&host=webapp.US&listenerId=&playedFrom=157&pname=live_profile&profileId=11554381129&stationid=1701&terminalId=159&territory=US
  placeholder2: 
    image: place2.png
  closed: 
    image: deadchannel.png
  error: 
    image: tverror.png
defaultChannel: 1

channels:

- number: 1
  name: texas wexas mexas
  pip:
    a:
      ref: placeholder
    b:
      video: https://ch3.tvs.gcpw.art/stream_480p.m3u8

- number: 2
  name: Program Guide
  title: Electronic Program Guide
  noise: 0.1
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3
  guide:
    theme: 1989
    themeOptions:
      title: Greenhill Cable TV Guide
      ticker: 
      - "Greenhill cable - connecting you to the future"
      - "Happy Viewing from Greenhill Cable!"
      - "Try out Watermelons! Now available at a grocery store near you!"
      - "Greenhill cable - you ever seen a buttersock?"

    
- number: 3
  name: Oak Ridge TV
  video: https://ch3.tvs.gcpw.art/stream_480p.m3u8


- number: 4
  name: Albuquerque
  video: https://cmd-hue.github.io/albuquerque.mp4

- number: 5
  name: Greenhill Public Access
  video: https://ch2.tvs.gcpw.art/stream_480p.m3u8
  backgroundAudio: https://cmd-hue.github.io/albuquerque.mp3


- number: 6
  name: Placeholder Channel
  ref: placeholder
  noise: 0.5

- number: 7
  name: Southwest Florida weather and live streaming webcams
  ref: error

- number: 8
  name: osd
  osd:
   tuner: true
   info: true
   receiver: true

- number: 9
  name: DirecTV ScreenSaver
  bouncing-logo: dtvlogo.webp

- number: 10
  name: Info Channel
  image: info.png

- number: 11
  abbr: CTV
  name: CMDTV
  iframe: 
   src: https://cmd-hue.github.io/cmdtv

- number: 12
  name: Weird Al Keno
  keno:
   drawingMinutes: 2
   drawIntervalMs: 800
   centerText: Weird Al Keno

- number: 13
  name: Audio Visualizer Test
  visualizer: https://cmd-hue.github.io/assets/joyfulblud.mp3

- number: 14
  name: Picsum Test
  image: https://fastly.picsum.photos/640/480

- number: 15
  name: Toon Goggles
  video: https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=37

- number: 16
  name: Toon Goggles Alternate
  video: https://stream-us-east-1.getpublica.com/playlist.m3u8?network_id=35

- number: 17
  name: Film4
  video: https://cache1a.netplus.ch/tok_eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIxNzcwMDQ1NDA2Iiwic2lwIjoiIiwicGF0aCI6Ii9saXZlL2Vkcy9maWxtNC9icm93c2VyLUhMUzgvIiwic2Vzc2lvbl9jZG5faWQiOiIzMDY3ZmQ3NjczMDM3Y2Y1Iiwic2Vzc2lvbl9pZCI6IiIsImNsaWVudF9pZCI6IiIsImRldmljZV9pZCI6IiIsIm1heF9zZXNzaW9ucyI6MCwic2Vzc2lvbl9kdXJhdGlvbiI6MCwidXJsIjoiaHR0cHM6Ly8xMC4wLjIyOS4xOSIsInNlc3Npb25fdGltZW91dCI6MCwiYXVkIjoiNTMiLCJzb3VyY2VzIjpbNDhdfQ==.Rqt_FNO-ecdsbnnVH-M_svUOQsYxyxTwMiZD3leg75LLuR4WXAzQPHaL0n46awJDj-93WBVGctMvSgkcFXP3kg==/live/eds/film4/browser-HLS8/film4.m3u8

  - number: 18
  name: News
  feed-reader:
    src: https://moxie.foxnews.com/google-publisher/us.xml
    title: News
    refreshInterval: 300
    scrollSpeed: 35
    scrollDelay: 6

- number: 19
  name: Nightwave Plaza
  description: Nightwave Plaza radio 24/7
  visualizer:
    src: http://radio.plaza.one/mp3 
    visualization: 100
    visualizationDuration: 0

- number: 20
  name: Fox Weather 24/7
  description: Nightwave Plaza video stream 24/7
  video: https://247wlive.foxweather.com/stream/index_640x360.m3u8

